### ISSUE TITLE
Frontend tests

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#43] opened 2017-01-24 23:16 UTC
We have some backend tests but it would be good if we could write some tests using something like selenium or phantom to test the frontend.

The tests I recommend adding are
- Make sure the vertical layout works
- Make sure the horizontal layout works
- Make sure the github link works
- Make sure the theme dropdown works (for all themes!)
- Make sure the examples dropdown works (for all examples!)

**Comment by patrick1011** [comment] 2017-01-25 15:14
Hey,

I fancy giving this a bash if that's okay?  I'm a first-timer but have done some test-writing before so think I'd be able to give this a decent shot!

Patrick

**Comment by tarang9211** [comment] 2017-01-25 15:17
@joshghent & @patrick1011 I suggest using Mocha and Chai to test the front end also. We are using that at work, and it seems to do the job pretty well.

**Comment by joshghent** [comment] 2017-01-25 15:57
@tarang9211 @patrick1011 Yeah use whatever framework is easiest. As long as they work!

**Comment by patrick1011** [comment] 2017-01-26 02:30
Great - i'll use Mocha!

**Comment by patrick1011** [comment] 2017-01-30 15:00
@joshghent @tarang9211 Just a quick update - I've written some tests in Mocha + Chai and Selenium to test the layout buttons and github links work.  It's going well.

One question though: what would you say constitutes a test for the dropdowns?  That the editor changes background colour/content based on what's clicked (themes/examples)?

**Comment by joshghent** [comment] 2017-01-30 15:31
@patrick1011 I mean in an ideal world then we would make sure that the correct classes get applied when changing the theme, but I think if you just add a test for one theme and then check it works correctly (i.e., the class has been applied, it doesn't matter about the colors that the editor now is) will be fine, thanks :)

**Comment by joshghent** [comment] 2017-02-16 21:18
@patrick1011 Hey there, have you had chance to work on this at all? It's ok if not, just want to check in and see if this is still in the works 👍

**Comment by tarang9211** [comment] 2017-02-20 17:01
@patrick1011 sorry for being so late to the party. In such cases, I have tested for the presence of the class name and that works. Let me know if you run into any issues!

**Comment by joshghent** [comment] 2017-02-21 13:10
@patrick1011 I'd advice using something like this http://nightwatchjs.org/
Mocha doesn't seem to have great syntax for checking css without mocking loads of stuff.

**Comment by SaraVieira** [comment] 2017-02-26 14:41
@joshghent I think we should use mocha for the tests and then supercharge later with some CSS regression tests with https://github.com/Huddle/PhantomCSS

The idea is that I think those two things should be split, unit tests and layout tests, what do you think ?

**Comment by joshghent** [comment] 2017-02-26 17:45
@SaraVieira Agreed, split them down. I agree with the different types of testing as well. Good to cover all aspects.

**Comment by SaraVieira** [comment] 2017-02-26 17:49
I'll create an issue for the Regression tests and assign it to me, because I have been meaning to play with that for a while 

@patrick1011 if you are still working on those mocha tests as unit tests that would be awesome and them I'll start on the CSS tests from the redesign branch 

@joshghent

**Comment by joshghent** [comment] 2017-02-26 17:56
Sounds good @SaraVieira. Look forward to hearing about your progress.

**Comment by collinmesser** [comment] 2017-07-25 11:25
@patrick1011 are you still working on this one? If not, no worries, just let us know and I will probably take it over.

**Comment by joshghent** [comment] 2017-08-08 17:57
@collinmesser Sorry I didn't pick up on this one. I'd say that it's free game. We'd love to get this checked off!

**Comment by AbubakarSaad** [comment] 2017-12-22 18:35
Is this issue still open? or some testing still left in front-end? I would love to take a shot at it!
Abu

**Comment by joshghent** [comment] 2018-02-06 14:09
@AbubakarSaad Yes sure thing! Go ahead! We'd love to have your help and would great appreciate this being done! 👍

**Comment by joshghent** [comment] 2018-04-12 17:29
@AbubakarSaad Hey there, I kind of let this issue drift but wanted to check in to see if you were doing ok with your PR and this issue? Can I or anyone else in the team help? Contact me on gitter if you need any assistance! 👍 

If you no longer have time to work on it, that's fine too. We appreciate people generously donate their precious free time to this!

**Closed** 2018-05-22 19:14 UTC
Labels: enhancement, first-timers-only, up-for-grabs
